# Generated by Django 3.2.4 on 2021-10-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_problem', models.CharField(max_length=150)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('problem_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naija.category')),
            ],
        ),
    ]
