# Generated by Django 3.2.4 on 2021-10-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naija', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('account_number', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_title', models.CharField(blank=True, max_length=255, null=True)),
                ('solution_text', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naija.problem')),
                ('solution_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='naija.profile')),
            ],
        ),
    ]
