# Generated by Django 3.2.4 on 2021-10-03 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('naija', '0002_profile_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='user_voted',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
